# Workflow name
name: "Publish"

on:

  # Triggers the workflow only for commits with a tag that starts with "v" (e.g "v1.0.0")
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:

  # This job will create a new GitHub release
  github-release:
    name: "Github Release"
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:

      - name: "📚 Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "📜 Generate Changelog"
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          args: -vv --latest --strip header

      - name: "📦 GitHub Release"
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          body: ${{ steps.git-cliff.outputs.content }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # This job will create an NPM release
  npm-publish:
    name: "NPM Publish"
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ github-release ]
    runs-on: ubuntu-latest

    steps:

      - name: "📚 Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "🟢 Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: "📦 NPM Publish"
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
